include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    always_use_package_imports: false
    unnecessary_null_checks: true
    use_key_in_widget_constructors: true
    sort_pub_dependencies: true
